### ISSUE TITLE
oriondsk 0.4.0?

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#21]
What is the status of updating this collection to support orionsdk v0.4.0? Will the current version of this collection support v0.4.0 or would stuff break if we updated the orionsdk to v0.4.0? We just updated our test Orion instance to 2024.2 and realized they changed the SWIS port in 2024.2 release from 17778 to 17774 and it broke our SolarWinds playbooks.

**Comment by jeisenbath** [comment]
thanks for reminding me, see #18 there is a branch ready I just didn't complete some testing on it. you should be able to install that branch and validate it for yourself.
