### ISSUE TITLE
Credential Set Issue

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#3]
It appears the orion_node module creates a unique snmpv3 credential set for each device added to Solarwinds even if you are assigning the same snmpv3 credentials to the difference nodes. If I am adding a large number of nodes, this will generate a lot of credential sets. I am not sure what the limit of the number of credential sets would be or when it would be a problem. However it is unnecessarily creating a credential set for each node when devices that share the same credentials could share the same credential set. 

Would it be possible to have a module to manage/create credential sets and then the orion_node module could assign that credential set to the node?

**Comment by Andyjb8** [comment]
It's interesting that after doing some imports with sets of nodes with the same snmpv3 credentials, it does seem to combine some, but not all of the node credential sets. For instance, in a handful of nodes I have added with the same credentials, it combined most of them and named them by including one of the device hostnames even though it's used by more than that device. It named the credential set in this format: "<snmpv3user>(<hostname>)" .  So if my snmpv3 user is "smpv3user1"  and I have nodes named rtr-01 etc. I see two different credential set names. "snmpuser1(rtr-01)" assigned to 3 nodes and "snmpuser1(rtr-02)" assigned to 12 nodes. Again it's interesting  that it chooses to combine some but not all snmpv3 credentials. It still would be nice to be able to manage credential sets and apply them to devices, allowing you to update snmpv3 credentials etc, but since its not actually creating a credential set for every device and so far hasn't caused me any issues, this is not a critical issue.

**Comment by jeisenbath** [comment]
I believe I have this functionality working in 1.0.3. I added a new required param snmpv3_credential_set, and confirmed that this groups credentials together.

The node creation API does still require you to pass the snmpv3 username, snmpv3 auth key, and snmpv3 private key, so these parameters are also required by the module. I tested trying to set a "placeholder" value for all of these, however that gives weird behavior where it creates a "placeholder" credential set and actually assigns both credential sets to the node. The only way it seems to work is if the username (at the very least, possibly both keys as well) in the credential set are also passed as values to the module.

I didn't have a working node to test the actual snmpv3 polling succeeds, only was able to confirm in the UI that the credential set seems to apply correctly. Hoping to do better testing this week.

**Comment by jeisenbath** [comment]
I was able to confirm this works to add a node with a Credential Set. Only caveat I ran into with testing is if the Credential Set doesn't already exist, it doesn't fail the module correctly, so I'll need to fix that.

**Comment by Andyjb8** [comment]
I just recently upgraded to 1.0.4 in my production and I ran into the above issue you mentioned where the credential set doesn't exist. It looks like the credential set is required to be defined before it can be used in the add node task. Is there a a way I can create the credential set first? I am generating my snmpv3 credential on the fly, so I need to be able to do this.  The less preferred option would be not require the credential set option like it was in previous release? Before it created a set that was unique per node even if it was the same credential (but sometimes it did group them under one set). That is not ideal and generated a lot of credential sets, but at least it worked.

**Comment by jeisenbath** [comment]
Hmm I didn't expect that to be the process. So psuedo code you:

```
- name: generate snmpv3 credentials

- name: Add node with generated credentials
```

If creating the credential set with the API is possible, it might be another instance where a seperate module would be best

```
- name: generate snmpv3 credentials

- name: add generated credential set to credential set library

- name: Add node with new credential set
```

**Comment by Andyjb8** [comment]
Yes, what you have there is correct.

**Comment by Andyjb8** [comment]
Because the credential set had to be defined and it was giving me issues, I have been using version 1.0.2 of the orion_node module (before the credential set was introduced)  Now that I am testing version 2.0.0 of the collection, I am realizing that I need to get my environment working with credential sets going forward. I have to many credential sets to pre-populate in Solarwinds and need to generate them on the fly. What is the effort to create a module that creates a credential set so I can do as you outlined above in psuedo code?

In testing I noticed that if I pass a credential set value that isn't defined in Solarwinds, I get this error, which is to be expected:
`IndexError: list index out of range`

However it still successfully adds the node to the SolarWinds inventory and snmpv3 polling works. As a possible easier short term solution, is there a reason the credential set has to be mandatory?

**Comment by Andyjb8** [comment]
As a workaround for now, I created and tested the attached orion_node module that doesn't require passing the snmpv3_credential_set (changed the extension to .txt as github wouldn't let me attach .py files)
[orion_node.txt](https://github.com/user-attachments/files/16020141/orion_node.txt)
